CREATE TABLE CLIENTES (
    CPF VARCHAR(11) PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ENDERECO VARCHAR(100),
    TELEFONE VARCHAR(11),
    RG VARCHAR (20),
    SITUACAO VARCHAR(60)
);

CREATE TABLE EDITORAS (
    ID INT PRIMARY KEY,
    NOME VARCHAR (100) NOT NULL,
    ENDERECO VARCHAR(100),
    TELEFONE VARCHAR(11)
);

CREATE TABLE LIVRO(
    ID INT PRIMARY KEY,
    TITULO VARCHAR(60),
    AUTOR VARCHAR(100),
    ANO INT,
    PRECO DECIMAL (10,2),
    QUANTIDADEESTOQUE INT,
    EDITORA INT,
    FOREIGN KEY (EDITORA) REFERENCES EDITORAS(ID)
);

CREATE TABLE PEDIDOS(
    ID INT PRIMARY KEY,
    DATA DATE,
    VALOR DECIMAL(10,2),
    SITUACAO VARCHAR(60),
    CLIENTE VARCHAR(20),
    FOREIGN KEY (CLIENTE) REFERENCES CLIENTES(CPF)
);

CREATE TABLE ITENSPEDIDO(
    LIVRO INT, 
    PEDIDO INT,
    QUANTIDADE INT,
    PRIMARY KEY (LIVRO, PEDIDO),
    FOREIGN KEY (LIVRO) REFERENCES LIVRO(ID),
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID)
);

CREATE TABLE LIVROSFALTA(
    ID INT PRIMARY KEY,
    NOME VARCHAR(100),
    AUTOR VARCHAR(100),
    ANO INT,
    ESTATUS VARCHAR(100),
    PEDIDO INT,
    FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID)
);

CREATE TABLE PEDIDOAQ (
    ID INT PRIMARY KEY,
    DATA DATE,
    VALOR DECIMAL(10,2),
    SITUACAO VARCHAR(60),
    EDITORA INT,
    FOREIGN KEY (EDITORA) REFERENCES EDITORAS(ID)
);

CREATE TABLE ITENSAQ (
    LIVRO_FALTA INT,
    PEDIDO_AQ INT,
    QUANTIDADE INT,
    PRIMARY KEY (LIVRO_FALTA, PEDIDO_AQ),
    FOREIGN KEY (LIVRO_FALTA) REFERENCES LIVROSFALTA(ID),
    FOREIGN KEY (PEDIDO_AQ) REFERENCES PEDIDOAQ(ID)
);